MAKEFLAGS = -j1

# Fix color output until TravisCI fixes https://github.com/travis-ci/travis-ci/issues/7967
export FORCE_COLOR = true

build: # Build script
lint: # Linting
test-ci-coverage: SHELL:=/bin/bash
test-ci-coverage:
	CHEROW_COVERAGE=true CHEROW_ENV=test make bootstrap
	CHEROWL_ENV=test TEST_TYPE=cov ./scripts/test-cov.sh
	bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json

bootstrap: clean-all
	yarn --ignore-engines
	./node_modules/.bin/lerna bootstrap -- --ignore-engines

bootstrap-cherow-tests:
bootstrap-cherow-ts-tests:
test-ci:
cherow-ts-tests:
cherow-ts-ci: bootstrap cherow-ts-tests
