import { Context } from '../../../src/common';
import { fail } from '../../test-utils';

describe('Miscellaneous - Early Errors', () => {
  fail('Miscellaneous - Early Errors', [
    ['"use strict"; function a(b, ...[b]){}', Context.Empty],
    // ['function* a(){ function* b({c = yield}){} }', Context.Empty],
    //  ['(class arguments {})', Context.Empty],
    ['const a = 1; let a;', Context.Empty],
    ['"use strict"; function a(...yield) {}', Context.Empty],
    // ['(function({a: b, c: b}){})', Context.Empty],
    ['"use strict"; !function*(a, a){}', Context.Empty],
    ['class a {static prototype(){}}', Context.Empty],
    ['for(const let in 1);', Context.Empty],
    ['switch(1) { case 2: let a; default: let a; }', Context.Empty],
    // ['({a}) => { const a = 1; }', Context.Empty],
    // ['function a(eval){ "use strict"; }', Context.Empty],
    [
      `"use strict";
    function a([a,a]){ }
    function a([a,...a]){ }
    function a([{a},...a]){ }`,
      Context.Empty
    ],
    ['const a = 1, b = 2, a = 3;', Context.Empty],
    //['([a],...a)=>1', Context.Empty],
    ['!{ a() { !function(a = super.b()){} } };', Context.Empty],
    ['"use strict"; function* eval(){}', Context.Empty],
    // ['try {} catch(a) { function a(){} }', Context.Empty],
    //['({a} += 0);', Context.Empty],
    ['switch(1) { case 2: const a = 3; default: var a; }', Context.Empty],
    ['function* a(){ !function*(b = yield){} }', Context.Empty],
    ['!{ get a() { "use strict"; +let; } }', Context.Empty],
    ['"use strict"; try {} catch (yield) {}', Context.Empty],
    ['class a extends b { constructor() { !{*constructor() { super(); }}; } }', Context.Empty],
    ['"use strict"; !function* arguments(){}', Context.Empty],
    ['function a() { "use strict"; public = 1; }', Context.Empty],
    ['function a() { "use strict"; function b(c, c) { }; }', Context.Empty],
    ['function* a(){ ({ *b(c = yield* d){} }); }', Context.Empty],
    ['for(a of b) d: function c(){}', Context.Empty],
    ['switch(1) { default: var a; case 2: let a; }', Context.Empty],
    ['"use strict"; +package;', Context.Empty],
    ['"use strict";  if (1) function a(){}', Context.Empty],
    ['function a(b, b) {"use strict";}', Context.Empty],
    ['var a; let a;', Context.Empty],
    ['(function () { "use strict"; with (a); }())', Context.Empty],
    ['"use strict"; (yield) => 1', Context.Empty],
    ['({a(b){}} = 0)', Context.Empty],
    ['function a(b){ const b = 1; }', Context.Empty],
    //['function a() {"use strict"; try { } catch (eval) { } }', Context.Empty],
    ['!{ __proto__: null, __proto__: null, };', Context.Empty],
    ['/./\\u{69}', Context.Empty],
    ['for(var a in b) d: function c(){}', Context.Empty],
    ['!{ *a(b = super()){} };', Context.Empty],
    ['const a = 1; var a;', Context.Empty],
    ['function* a(){ function* b(c = yield* d){} }', Context.Empty],
    ['class a { static b(){ let c; var c; } }', Context.Empty],
    ['{ const a = 1; var a; }', Context.Empty],
    ['{ function a(){} function* a(){} }', Context.OptionsDisableWebCompat],
    ['"use strict"; (a = yield) => {}', Context.Empty],
    ['for(const a of 1) { var a; }', Context.Empty],
    ['"use strict"; function a(__proto__, __proto__) { }', Context.Empty],
    ['"use strict"; var { a: yield } = b;', Context.Empty],
    ['if(1) b: function a(){} else ;', Context.Empty],
    ['({ __proto__: null, __proto__: null })', Context.Empty],
    ['switch(1) { default: let a; case 2: var a; }', Context.Empty],
    ['for (const let in a);', Context.Empty],
    ['[...new a] = 0;', Context.Empty],
    //    ['function* a(){ ({ *b({c = yield}){} }); }', Context.Empty],
    ['while(1) continue a;', Context.Empty],
    ['let a; const a = 1;', Context.Empty],
    ['for(const a = 1, let = 2;;);', Context.Empty],
    ['!{ set a({b, b}){} };', Context.Empty],
    ['switch(1) { case 2: var a; case 3: let a; }', Context.Empty],
    // ['function* a(){ !function*({[yield]: b}){} }', Context.Empty],
    ['"use strict"; +implements;', Context.Empty],
    ['class a extends b { c() { !function* (){ super.d(); } } }', Context.Empty],
    ['for(const a = 1;;) c: function b(){}', Context.Empty],
    //    ['switch(1) { default: !function(){ break; }; }', Context.Empty],
    ['class a extends b { c() { function* d(){ super.e(); } } }', Context.Empty],
    ['switch(1) { default: const a = 2; case 3: var a; }', Context.Empty],
    ['class a {static [static](){};}', Context.Empty],
    // ['function* a(){ ({ *b(c = d + e(yield)){} }); }', Context.Empty],
    ['({get a(){}} = 0)', Context.Empty],
    ['!function* a(b = super()){}', Context.Empty],
    ['!function* a(b) { super() }', Context.Empty],
    //['class a { get constructor() {} }', Context.Empty],
    ['try {} catch ({a, a}) {}', Context.Empty],
    ['eval => {"use strict"};', Context.Empty],
    ['"use strict"; function a({ b: { c } }, [{ b: { c } }]){}', Context.Empty],
    //['function a() {"use strict"; ({ b: function b(eval) { } }); }', Context.Empty],
    //    ['class a extends (eval = null) { };', Context.Empty],
    ['!{ a() { function* b(a = super.c()){} } };', Context.Empty],
    ['({ a(){ super(); } });', Context.Empty],
    ['let a, let;', Context.Empty],
    ['class a extends b { static c() { super(); } }', Context.Empty],
    ['switch(1) { default: let a; case 2: function a(){} }', Context.Empty],
    ['try {} catch ({a: b, c: b}) {}', Context.Empty],
    ['{ let a; let a; }', Context.Empty],
    ['function a() { "use strict"; var package; }', Context.Empty],
    ['let a, b, a;', Context.Empty],
    ['!{ __proto__: null, __proto__: null };', Context.Empty],
    ['break a;', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['({ a = 0 });', Context.Empty],
    ['(...a)', Context.Empty],
    ['(a, ...b)', Context.Empty],
    ['(((a, ...b)))', Context.Empty],
    ['0++', Context.Empty],
    ['++0', Context.Empty],
    ['({set a(b){}} = 0)', Context.Empty],
    ['function t(true) { }', Context.Empty],
    ['({a(b){}} = 0)', Context.Empty],
    ['[0] = 0;', Context.Empty],
    ['0 = 0;', Context.Empty],
    ['({a}) = 0;', Context.Empty],
    ['([a]) = 0;', Context.Empty],
    ['[...{a: 0}] = 0;', Context.Empty],
    ['[...[0]] = 0;', Context.Empty],
    ['[...0] = 0;', Context.Empty],
    ['[...new a] = 0;', Context.Empty],
    ['for({a: 0} in 0);', Context.Empty],
    ['for([0] in 0);', Context.Empty],
    ['for({a: 0} of 0);', Context.Empty],
    ['for([0] of 0);', Context.Empty],
    ['{ let a; let a; }', Context.Empty],
    ['{ let a; const a = 0; }', Context.Empty],
    ['{ function a(){} function a(){} }', Context.OptionsDisableWebCompat],
    ['{ let a; function a(){} }', Context.Empty],
    ['class o {f(b, a, b, ...a) {}}', Context.Empty],
    ['class o {f([b, a], b=x) {}}', Context.Empty],
    ['class o {f([b, a], ...b) {}}', Context.Empty],
    ['class o {f(){ const x = y; var x; }}', Context.Empty],
    ['class o {f(){ function x(){} const x = y; }}', Context.Empty],
    ['var x = a; let x = b;', Context.Empty],
    ['const x = a; const x = b;', Context.Empty],
    ['{ function f(){} function f(){} }', Context.OptionsDisableWebCompat],
    ['class o {f(){ function x(){} const x = y; }}', Context.Empty],
    ['var x = a; let x = b;', Context.Empty],
    ['{ let a; var a; }', Context.Empty],
    ['{ let a; { var a; } }', Context.Empty],
    ['{ var a; let a; }', Context.Empty],
    ['{ const a = 0; var a; }', Context.Empty],
    ['{ var a; const a = 0; }', Context.Empty],
    ['let let;', Context.Empty],
    ['let a, let;', Context.Empty],
    ['let a, let = 0;', Context.Empty],
    ['for(let let;;);', Context.Empty],
    ['for(let a, let;;);', Context.Empty],
    ['for(const let = 0;;);', Context.Empty],
    ['for(const a = 0, let = 1;;);', Context.Empty],
    ['for(let [let] = 0;;);', Context.Empty],
    ['let a, a;', Context.Empty],
    ['let a, b, a;', Context.Empty],
    ['let a = 0, a = 1;', Context.Empty],
    ['const a = 0, a = 1;', Context.Empty],
    ['const a = 0, b = 1, a = 2;', Context.Empty],
    ['let a, [a] = 0;', Context.Empty],
    ['let [a, a] = 0;', Context.Empty],
    ['let {a: b, c: b} = 0;', Context.Empty],
    ['for(var a of b) label: function f(){}', Context.Empty],
    ['for(let let of 0);', Context.Empty],
    ['for(const {a, a} in 0);', Context.Empty],
    ['let {a: b, c: b} = 0;', Context.Empty],
    ['let {a: b, c: b} = 0;', Context.Empty],
    ['let {a: b, c: b} = 0;', Context.Empty],
    ['switch(0) { case 0: let a; case 1: let a; }', Context.Empty],
    ['switch(0) { case 0: let a; case 1: function a(){} }', Context.Empty],
    ['switch(0) { case 0: let a; default: let a; }', Context.Empty],
    ['switch(0) { default: let a; case 0: let a; }', Context.Empty],
    ['switch(0) { default: let a; case 0: function a(){} }', Context.Empty],
    ['switch(0) { default: function a(){} case 0: let a  }', Context.Empty],
    ['switch(0) { default: function a(){} case 0: let a  }', Context.Empty],
    ['switch(0) { case 0: let a; case 1: var a; }', Context.Empty],
    ['switch(0) { case 0: var a; case 1: let a; }', Context.Empty],
    ['switch(0) { case 0: let a; default: var a; }', Context.Empty],
    ['switch(0) { case 0: var a; default: let a; }', Context.Empty],
    ['switch(0) { default: let a; case 0: var a; }', Context.Empty],
    ['switch(0) { default: var a; case 0: let a; }', Context.Empty],
    ['switch(0) { case 0: const a = 0; case 1: var a; }', Context.Empty],
    ['switch(0) { case 0: var a; case 1: const a = 0; }', Context.Empty],
    ['switch(0) { case 0: const a = 0; default: var a; }', Context.Empty],
    ['switch(0) { case 0: var a; default: const a = 0; }', Context.Empty],
    ['switch(0) { default: const a = 0; case 0: var a; }', Context.Empty],
    ['switch(0) { default: var a; case 0: const a = 0; }', Context.Empty],
    ['try {} catch ([e, e]) {}', Context.Empty],
    ['try {} catch ({e, e}) {}', Context.Empty],
    ['try {} catch ({a: e, b: e}) {}', Context.Empty],
    ['try {} catch ({e = 0, a: e}) {}', Context.Empty],
    ['function f(a){ let a; }', Context.Empty],
    ['function f(a){ const a = 0; }', Context.Empty],
    ['!function(a){ let a; }', Context.Empty],
    ['!function(a){ const a = 0; }', Context.Empty],
    ['function f(a = super.b){}', Context.Empty],
    ['!function f(a = super[0]){}', Context.Empty],
    ['!function(a = super.b){}', Context.Empty],
    ['!{ a() { function f(a = super.b()){} } };', Context.Empty],
    ['!{ a() { !function(a = super.b()){} } };', Context.Empty],
    ['class A extends B { a() { function f(a = super.b()){} } }', Context.Empty],
    ['function f(a){ super.b }', Context.Empty],
    ['!function f(a){ super[0] }', Context.Empty],
    ['!function(a){ super.b }', Context.Empty],
    ['!{ a() { function f(){ super.b(); } } };', Context.Empty],
    ['!{ a() { !function(){ super.b(); } } };', Context.Empty],
    ['class A extends B { a() { function f(){ super.b(); } } }', Context.Empty],
    ['class A extends B { a() { !function(){ super.b(); } } }', Context.Empty],
    ['function f(a = super()){}', Context.Empty],
    ['!function(a = super()){}', Context.Empty],
    ['function f(a){ super() }', Context.Empty],
    ['!function(a){ super() }', Context.Empty],
    ['!{ f(a, a){} };', Context.Empty],
    ['!{ f([a, a]){} };', Context.Empty],
    ['!{ f({a, a}){} };', Context.Empty],
    ['!{ *g(a, a){} };', Context.Empty],
    ['!{ *g([a, a]){} };', Context.Empty],
    ['!{ *g({a, a}){} };', Context.Empty],
    ['class A { static f(a, a){} }', Context.Empty],
    ['class A { static f([a, a]){} }', Context.Empty],
    ['class A { static f({a, a}){} }', Context.Empty],
    ['function f(){ let a; let a; }', Context.Empty],
    ['function f(){ let a; const a = 0; }', Context.Empty],
    ['function f(){ const a = 0; let a; }', Context.Empty],
    ['function f(){ const a = 0; const a = 0; }', Context.Empty],
    ['!function f(){ let a; let a; }', Context.Empty],
    ['!{ f(){ let a; let a; } };', Context.Empty],
    ['!{ *g(){ let a; let a; } };', Context.Empty],
    ['!{ get f(){ let a; let a; } };', Context.Empty],
    ['!{ set f(b){ let a; let a; } };', Context.Empty],
    ['class A { static f(){ let a; let a; } }', Context.Empty],
    ['() => { let a; let a; }', Context.Empty],
    ['function f(){ let a; var a; }', Context.Empty],
    ['function f(){ var a; let a; }', Context.Empty],
    ['function f(){ const a = 0; var a; }', Context.Empty],
    ['function f(){ var a; const a = 0; }', Context.Empty],
    ['!function f(){ let a; var a; }', Context.Empty],
    ['!{ f(){ let a; var a; } };', Context.Empty],
    ['!{ *g(){ let a; var a; } };', Context.Empty],
    ['!{ get f(){ let a; var a; } };', Context.Empty],
    ['!{ set f(b){ let a; var a; } };', Context.Empty],
    ['class A { static f(){ let a; var a; } }', Context.Empty],
    ['() => { let a; var a; }', Context.Empty],
    ['!{ f(a) { let a; } };', Context.Empty],
    ['!{ f([a]){ let a; } };', Context.Empty],
    ['!{ f({a}){ let a; } };', Context.Empty],
    ['!{ set f({a, a}){} };', Context.Empty],
    ['!{ set f([a, a]){} };', Context.Empty],
    ['!{ set f(a) { let a; } };', Context.Empty],
    ['!{ set f([a]){ let a; } };', Context.Empty],
    ['!{ set f({a}){ let a; } };', Context.Empty],
    ['function* f(a) { let a; }', Context.Empty],
    ['function* f([a]){ let a; }', Context.Empty],
    ['function* f({a}){ let a; }', Context.Empty],
    ['class A { constructor(){} constructor(){} }', Context.Empty],
    ['class A { constructor(){} "constructor"(){} }', Context.Empty],
    ['!class A { constructor(){} constructor(){} }', Context.Empty],
    ['!class A { constructor(){} "constructor"(){} }', Context.Empty],
    ['class A extends B { static f() { super(); } }', Context.Empty],
    ['class A extends B { static prototype(){} }', Context.Empty],
    ['class A extends B { static *prototype(){} }', Context.Empty],
    ['class A extends B { static get prototype(){} }', Context.Empty],
    ['class A extends B { static set prototype(a) {} }', Context.Empty],
    ['let a; let a;', Context.Empty],
    ['let a; const a = 0;', Context.Empty],
    ['const a = 0; let a;', Context.Empty],
    ['const a = 0; const a = 0;', Context.Empty],
    ['let a; var a;', Context.Empty],
    ['var a; let a;', Context.Empty],
    ['const a = 0; var a;', Context.Empty],
    ['var a; const a = 0;', Context.Empty]
  ]);
});
