export const enum Errors {
    Unexpected,
    InvalidOrUnexpectedToken,
    UnexpectedTokenIdentifier,
    UnexpectedToken,
    UnterminatedComment,
    UnterminatedString,
    UnterminatedRegExp,
    UnicodeOutOfRange,
    InvalidUnicodeEscapeSequence,
    StrictOctalEscape,
    InvalidEightAndNine,
    StrictOctalLiteral,
    MissingShebangExclamation,
    DuplicateRegExpFlag,
    UnexpectedTokenRegExp,
    UnexpectedTokenRegExpFlag,
    BadImportCallArity,
    StrictFunction,
    BadContinue,
    IllegalBreak,
    MultipleDefaultsInSwitch,
    IllegalReturn,
    NoCatchOrFinally,
    LineBreakAfterThrow,
    StrictModeWith,
    BadGetterArity,
    BadSetterArity,
    BadSetterRestParameter,
    IllegalUseStrict,
    ParameterAfterRestParameter,
    StrictFunctionName,
    MetaNotInFunctionBody,
    DeclarationMissingInitializer,
    InvalidVarInitForOf,
    InvalidLHSInForLoop,
    InvalidLHSInForIn,
    InvalidLHSInForOf,
    StrictLHSAssignment,
    InvalidLHSInAssignment,
    NoAsAfterImportNamespace,
    InvalidModuleSpecifier,
    NonEmptyJSXExpression,
    ExpectedJSXClosingTag,
    AdjacentJSXElements,
    InvalidBinaryDigit,
    InvalidOctalDigit,
    StrictDelete,
    StrictLHSPrefix,
    StrictLHSPostfix,
    StrictFormalParameter,
    ExportDeclAtTopLevel,
    ImportDeclAtTopLevel,
    MissingMsgDeclarationAfterExport,
    ForAwaitNotOf,
    LetInLexicalBinding,
    DuplicateProtoProperty,
    StrictParamDupe,
    InvalidHexEscapeSequence,
    ConstructorSpecialMethod,
    BadSuperCall,
    UnexpectedSuper,
    DuplicateConstructor,
    StaticPrototype,
    MissingClassName,
    ClassDeclarationNoName,
    LineBreakAfterAsync,
    UnexpectedEscapedKeyword,
    MissingArrowAfterParentheses,
    InvalidParenthesizedPattern,
    DuplicateIdentifier,
    DuplicateBinding,
    Redeclaration,
    UnknownLabel,
    UnexpectedReservedWord,
    InvalidShorthandAssignment,
    UnterminatedTemplate,
    UnexpectedStrictReserved,
    StrictParamName,
    DisallowedInContext,
    IllegalArrowInParamList,
    UnexpectedBigIntLiteral,
    UnNamedClassStmt,
    UnNamedFunctionStmt,
    InvalidStrictExpPostion,
    InvalidBindingStrictMode,
    MissingInitializer,
    InvalidVarDeclInForLoop,
    UnexpectedNumber,
    UnexpectedSurrogate,
    ForbiddenAsStatement,
    InvalidAsyncGenerator,
    InvalidArrowYieldParam,
    InvalidAwaitInArrowParam,
    UnsupportedFeature,
    TemplateOctalLiteral,
    InvalidNestedStatement,
    InvalidGeneratorParam,
    DefaultRestParameter,
    IllegalArrowFuncParamList,
    ReservedKeyword,
    InvalidPrivateConstructor,
    InvalidAwaitInAsyncFunc,
    NewTargetArrow,
    UndefinedInClassScope,
    InvalidComputedClassProperty,
    InvalidFieldConstructor,
    InvalidNumericSeparators,
    InvalidRestDefaultValue,
    InvalidBigIntLiteral,
    InvalidLhsInPostfixOp,
    InvalidLhsInPrefixOp,
    InvalidDestructuringTarget,
    UnterminatedEscape,
    NoRegExpRepGrpToTerminate,
    NoRegExpRepitation,
    UnmatchedRegExpGroupName,
    InvalidRegExpGroup,
    AsyncFunctionInSingleStatementContext,
    GeneratorInSingleStatementContext,
    SloppyFunction,
    YieldInParameter,
    InvalidRestBindingPattern,
    ElementAfterRest,
    ForInOfLoopMultiBindings,
    ParenAfterIf,
    ParenAfterWith,
    ParenAfterFor,
    ParenAfterDoWhile,
    MissingBinaryDigits,
    MissingOctalDigits,
    MissingHexDigits
}

export const ErrorMessages: {
    [key: string]: string
} = {
    [Errors.Unexpected]: 'Unexpected token',
    [Errors.InvalidOrUnexpectedToken]: 'Invalid or unexpected token',
    [Errors.UnexpectedTokenIdentifier]: 'Unexpected identifier',
    [Errors.UnexpectedToken]: 'Unexpected token \'%0\'',
    [Errors.UnterminatedComment]: 'Unterminated comment',
    [Errors.UnterminatedString]: 'Unterminated string literal',
    [Errors.UnterminatedRegExp]: 'Unterminated regular expression literal',
    [Errors.UnicodeOutOfRange]: 'Unicode escape code point out of range',
    [Errors.InvalidUnicodeEscapeSequence]: 'Invalid Unicode escape sequence',
    [Errors.StrictOctalEscape]: 'Octal escapes are not allowed in strict mode',
    [Errors.InvalidEightAndNine]: 'Escapes \\8 or \\9 are not syntactically valid escapes',
    [Errors.StrictOctalLiteral]: 'Octal literals are not allowed in strict mode',
    [Errors.MissingShebangExclamation]: 'Missing exclamation in shebang',
    [Errors.DuplicateRegExpFlag]: 'Duplicate regular expression flag %0',
    [Errors.UnexpectedTokenRegExp]: 'Unexpected regular expression',
    [Errors.UnexpectedTokenRegExpFlag]: 'Unexpected regular expression flag',
    [Errors.BadImportCallArity]: 'Dynamic import must have one specifier as an argument',
    [Errors.StrictFunction]: 'In strict mode code, functions can only be declared at top level or inside a block',
    [Errors.BadContinue]: 'Continue must be inside loop or switch statement',
    [Errors.IllegalBreak]: 'Unlabeled break must be inside loop or switch',
    [Errors.IllegalReturn]: 'Illegal return statement',
    [Errors.MultipleDefaultsInSwitch]: 'More than one default clause in switch statement',
    [Errors.NoCatchOrFinally]: 'Missing catch or finally after try',
    [Errors.LineBreakAfterThrow]: 'No line break is allowed between \'throw\' and its expression',
    [Errors.StrictModeWith]: 'Strict mode code may not include a with statement',
    [Errors.BadGetterArity]: 'Getter must not have any formal parameters',
    [Errors.BadSetterArity]: 'Setter must have exactly one formal parameter',
    [Errors.BadSetterRestParameter]: 'Setter function argument must not be a rest parameter',
    [Errors.IllegalUseStrict]: 'Illegal \'use strict\' directive in function with non-simple parameter list',
    [Errors.ParameterAfterRestParameter]: 'Rest parameter must be last formal parameter',
    [Errors.StrictFunctionName]: 'Function name may not be eval or arguments in strict mode code',
    [Errors.MetaNotInFunctionBody]: 'new.target only allowed within functions',
    [Errors.DeclarationMissingInitializer]: 'Missing initializer in destructuring declaration',
    [Errors.InvalidLHSInForLoop]: 'Invalid left-hand side in for-loop',
    [Errors.InvalidVarInitForOf]: 'for-of loop variable declaration may not have an initializer',
    [Errors.InvalidLHSInForOf]: 'Invalid left-hand side in for-of',
    [Errors.InvalidLHSInForIn]: 'Invalid left-hand side in for-in',
    [Errors.StrictLHSAssignment]: 'Eval or arguments can\'t be assigned to in strict mode code',
    [Errors.InvalidLHSInAssignment]: 'Invalid left-hand side in assignment',
    [Errors.MissingArrowAfterParentheses]: 'Missing => after parentheses',
    [Errors.NoAsAfterImportNamespace]: 'Missing \'as\' keyword after import namespace',
    [Errors.InvalidModuleSpecifier]: 'Invalid module specifier',
    [Errors.NonEmptyJSXExpression]: 'JSX attributes must only be assigned a non-empty  \'expression\'',
    [Errors.ExpectedJSXClosingTag]: 'Expected corresponding JSX closing tag for %0',
    [Errors.AdjacentJSXElements]: 'Adjacent JSX elements must be wrapped in an enclosing tag',
    [Errors.InvalidBinaryDigit]: 'Invalid binary digit',
    [Errors.InvalidOctalDigit]: 'Invalid octal digit',
    [Errors.StrictDelete]: 'Identifier expressions must not be deleted in strict mode',
    [Errors.StrictLHSPrefix]: 'Prefix increment/decrement may not have eval or arguments operand in strict mode',
    [Errors.StrictLHSPostfix]: 'Postfix increment/decrement may not have eval or arguments operand in strict mode',
    [Errors.ExportDeclAtTopLevel]: 'Export declarations may only appear at top level of a module',
    [Errors.ImportDeclAtTopLevel]: 'Import declarations may only appear at top level of a module',
    [Errors.MissingMsgDeclarationAfterExport]: 'Missing declaration after \'export\' keyword',
    [Errors.ForAwaitNotOf]: 'For await loop should be used with \'of\'',
    [Errors.LetInLexicalBinding]: 'let is disallowed as a lexically bound name',
    [Errors.DuplicateProtoProperty]: 'Property name __proto__ appears more than once in object literal',
    [Errors.StrictParamDupe]: 'Duplicate argument names not allowed in this context',
    [Errors.InvalidHexEscapeSequence]: 'Invalid hexadecimal escape sequence',
    [Errors.ConstructorSpecialMethod]: 'Class constructor may not be an accessor',
    [Errors.BadSuperCall]: 'super() is only valid in derived class constructors',
    [Errors.UnexpectedSuper]: '\'super\' keyword unexpected here',
    [Errors.DuplicateConstructor]: 'A class may only have one constructor',
    [Errors.StaticPrototype]: 'Classes may not have static property named prototype',
    [Errors.LineBreakAfterAsync]: 'No line break is allowed after async',
    [Errors.UnexpectedEscapedKeyword]: 'Unexpected escaped keyword',
    [Errors.InvalidParenthesizedPattern]: 'Invalid parenthesized pattern',
    [Errors.DuplicateIdentifier]: '\'%0\' has already been declared ',
    [Errors.DuplicateBinding]: 'Duplicate binding %0',
    [Errors.Redeclaration]: 'Label \'%0\' has already been declared',
    [Errors.UnknownLabel]: 'Undefined label \'%0\'',
    [Errors.UnexpectedReservedWord]: 'Unexpected reserved word',
    [Errors.InvalidShorthandAssignment]: 'Shorthand property assignments are valid only in destructuring patterns',
    [Errors.UnterminatedTemplate]: 'Unterminated template literal',
    [Errors.UnexpectedStrictReserved]: 'Unexpected eval or arguments in strict mode',
    [Errors.StrictParamName]: 'The identifier \'eval\' or \'arguments\' must not be in binding position in strict mode',
    [Errors.DisallowedInContext]: '\'%0\' may not be used as an identifier in this context',
    [Errors.IllegalArrowInParamList]: 'Illegal arrow function parameter list',
    [Errors.UnexpectedBigIntLiteral]: 'Unexpected BigInt literal',
    [Errors.UnNamedClassStmt]: 'Class statement requires a name',
    [Errors.UnNamedFunctionStmt]: 'Function statement requires a name',
    [Errors.InvalidStrictExpPostion]: 'The identifier \'%0\' must not be in expression position in strict mode',
    [Errors.InvalidBindingStrictMode]: 'The identifier \'%0\' must not be in binding position in strict mode',
    [Errors.MissingInitializer]: 'Missing initializer',
    [Errors.InvalidVarDeclInForLoop]: 'Invalid variable declaration in for-%0 statement',
    [Errors.UnexpectedNumber]: 'Unexpected number',
    [Errors.UnexpectedSurrogate]: 'Unexpected surrogate pair',
    [Errors.ForbiddenAsStatement]: '%0 can\'t appear in single-statement context',
    [Errors.InvalidAsyncGenerator]: 'Generator function or method can\'t be async',
    [Errors.InvalidArrowYieldParam]: 'Arrow parameters must not contain yield expressions',
    [Errors.InvalidAwaitInArrowParam]: '\'await\' is not a valid identifier name in an async function',
    [Errors.UnsupportedFeature]: '%0 isn\'t supported by default. Enable the \'%1\' option to use them',
    [Errors.TemplateOctalLiteral]: 'Template literals may not contain octal escape sequences',
    [Errors.InvalidNestedStatement]: '%0  statement must be nested within an iteration statement',
    [Errors.InvalidGeneratorParam]: 'Generator parameters must not contain yield expressions',
    [Errors.IllegalArrowFuncParamList]: 'Illegal arrow function parameter list',
    [Errors.ReservedKeyword]: 'The keyword %0 is reserved',
    [Errors.InvalidPrivateConstructor]: 'Class constructor may not have a private field',
    [Errors.InvalidAwaitInAsyncFunc]: 'Can not use await as identifier inside an async function',
    [Errors.NewTargetArrow]: 'new.target must be within function (but not arrow expression) code',
    [Errors.UndefinedInClassScope]: '\'%0\'  not defined in class scope',
    [Errors.InvalidComputedClassProperty]: 'Invalid computed name in private property',
    [Errors.InvalidFieldConstructor]: 'Classes may not have a private field named \'#constructor\'',
    [Errors.InvalidNumericSeparators]: 'Numeric separators are not allowed here',
    [Errors.InvalidRestDefaultValue]: 'Rest elements cannot have a default value',
    [Errors.InvalidBigIntLiteral]: 'Invalid BigIntLiteral',
    [Errors.InvalidLhsInPostfixOp]: 'Invalid left-hand side expression in postfix operation',
    [Errors.InvalidLhsInPrefixOp]: 'Invalid left-hand side expression in prefix operation',
    [Errors.InvalidDestructuringTarget]: 'Invalid destructuring assignment target',
    [Errors.UnterminatedEscape]: 'Unterminated escape in regular expression',
    [Errors.AsyncFunctionInSingleStatementContext]: 'Async functions can only be declared at the top level or inside a block',
    [Errors.InvalidRegExpGroup]: 'Generators can only be declared at the top level or inside a block',
    [Errors.GeneratorInSingleStatementContext]: 'Generators can only be declared at the top level or inside a block.',
    [Errors.SloppyFunction]: 'In non-strict mode code, functions can only be declared at top level, inside a block, or as the body of an if statement',
    [Errors.YieldInParameter]: 'Yield expression not allowed in formal parameter',
    [Errors.InvalidRestBindingPattern]: '`...` must be followed by an identifier in declaration contexts',
    [Errors.ElementAfterRest]: 'Rest element must be last element',
    [Errors.ForInOfLoopMultiBindings]: 'Invalid left-hand side in %0 loop: Must have a single binding.',
    [Errors.ParenAfterIf]: 'missing ) after if-statement',
    [Errors.ParenAfterWith]: 'missing ) after with-statement',
    [Errors.ParenAfterFor]: 'missing ) after for-loop head',
    [Errors.ParenAfterDoWhile]: 'missing ) after do-while',
    [Errors.MissingBinaryDigits]: 'Missing binary digits after \'0b\'',
    [Errors.MissingOctalDigits]: 'Missing octal digits after \'0o\'',
    [Errors.MissingHexDigits]: 'Missing hexadecimal digits after \'0x\'',

    
};

function constructError(msg: string, column: number): Error {
    let error: Error = new Error(msg);
    try {
        throw error;
    } catch (base) {
        // istanbul ignore else
        if (Object.create && Object.defineProperty) {
            error = Object.create(base);
            Object.defineProperty(error, 'column', {
                enumerable: true,
                writable: true,
                value: column
            });
        }
    }
    // istanbul ignore next
    return error;
}
export function createError(type: Errors, loc: any, ...params: string[]): Error {
    const description = ErrorMessages[type].replace(/%(\d+)/g, (_: string, i: number) => params[i]);
    const error: any = constructError('Line ' + loc.line + ': ' + description, loc.column);

    error.index = loc.index;
    error.lineNumber = loc.line;
    error.description = description;
    error.column = loc.column;
    return error;
}